version: '3.8'

services:
  movies:
    build: 
      context: .
      dockerfile: services/movies/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./database:/app/database
    environment:
      - FLASK_APP=services.movies
      - FLASK_ENV=development
      - PORT=5001

  showtimes:
    build:
      context: .
      dockerfile: services/showtimes/Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./database:/app/database
    environment:
      - FLASK_APP=services.showtimes
      - FLASK_ENV=development
      - PORT=5002

  bookings:
    build:
      context: .
      dockerfile: services/bookings/Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./database:/app/database
    environment:
      - FLASK_APP=services.bookings
      - FLASK_ENV=development
      - PORT=5003

  users:
    build:
      context: .
      dockerfile: services/users/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./database:/app/database
    environment:
      - FLASK_APP=services.users
      - FLASK_ENV=development
      - PORT=5000
    depends_on:
      - movies
      - showtimes
      - bookings 